import getpass
from typing import List

from ecosuite_python import AuthenticatedClient
from ecosuite_python.api.project import projects
from ecosuite_python.models.error import Error
from ecosuite_python.models.project import Project
from ecosuite_python.types import Response

from pycognito import Cognito
from pycognito.exceptions import SoftwareTokenMFAChallengeException

username = input("Ecosuite username: ")

# The first two parameters are fixed
u = Cognito('us-east-1_7BBBhGf1p','6fk3ot5ut181jt7r2pdp9h6m5q', username=username)

# It's likely that we need to handle a MFA
try:
    u.authenticate(password=getpass.getpass())
except SoftwareTokenMFAChallengeException as error:
    code = getpass.getpass(prompt='Enter the 6-digit code generated by the TOTP generator (such as Google Authenticator): ')
    resp = u.respond_to_software_token_mfa_challenge(code)

print("Authenticated with Ecosuite")

# Use the id token for the Authorization header
client = AuthenticatedClient(base_url="https://api.ecosuite.io", token=u.id_token)

# Use the async function if needed
result = projects.sync(client=client)

if isinstance(result, Error):
    print(f'Failed to fetch projects: ${result.message}')
else:
    if result is None:
        print("Projects missing from response")
    else:
        if isinstance(result.projects, List):
            l = len(result.projects)
            print(f'Fetched {l}:')
            for project in result.projects:
                print(f'{project.name} -> {project.code}')


