import getpass
from pycognito import Cognito
from pycognito.exceptions import SoftwareTokenMFAChallengeExceptionusername = input("Ecosuite username: ")# The first two parameters are fixed
u = Cognito('us-east-1_7BBBhGf1p','6fk3ot5ut181jt7r2pdp9h6m5q', username=username)# It's likely that we need to handle a MFA
try:
    u.authenticate(password=getpass.getpass())
except SoftwareTokenMFAChallengeException as error:
    code = getpass.getpass(prompt='Enter the 6-digit code generated by the TOTP generator (such as Google Authenticator): ')
    resp = u.respond_to_software_token_mfa_challenge(code)print("Authenticated with Ecosuite")
print(f"ID Token: {u.id_token}")